### ISSUE TITLE
Get alltime stats

### ISSUE THREAD

**Issue by freekmurze** [Developmint/npm-stats-api#1]
Is it possible to get stats starting from a given date? Eg. give me a total of downloads of a package starting from 1/1/2014?

**Comment by TheAlexLichter** [comment]
Yeah, this is possible by using a range from 1/1/2015 (which is the earliest date provided) to the current date (which can be found out programmatically):

``` php 
$currentDate = (new \DateTime)->format("Y-m-d");
$npmStats->getStats('vue-save-state', "2015-01-01:{$currentDate}");
```

PS: I'll add a passing test for that one in a second.
